version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always

  flaskapp:
    build: .
    container_name: flaskapp
    ports:
      - "5002:5000"

volumes:
  grafana-storage:
    driver: local