name: Push test

on:
  push:
    branches:
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start app in background
        run: |
          python app.py &  # Indítás háttérben
          APP_PID=$!
          echo "App PID: $APP_PID"
          sleep 5  # Várunk, hogy fusson egy kicsit
          kill $APP_PID  # Leállítás
          echo "App stopped."

      